# Pass only variable names so build logs never expand dependency credentials.
# GIT_CONFIG_PARAMETERS also works with the legacy SDK builder's Git.
PRIVATE_GO_DOCKER_ENV := -e GOPRIVATE -e GO_DEPENDENCY_TOKEN -e GIT_CONFIG_PARAMETERS -e GIT_CONFIG_COUNT -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0
PRIVATE_GO_SUDO_ENV := --preserve-env=GOPRIVATE,GO_DEPENDENCY_TOKEN,GIT_CONFIG_PARAMETERS,GIT_CONFIG_COUNT,GIT_CONFIG_KEY_0,GIT_CONFIG_VALUE_0
