# Pass only variable names so build logs never expand dependency credentials.
PRIVATE_GO_DOCKER_ENV := -e GOPRIVATE -e GO_DEPENDENCY_TOKEN -e GIT_CONFIG_COUNT -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1
PRIVATE_GO_SUDO_ENV := --preserve-env=GOPRIVATE,GO_DEPENDENCY_TOKEN,GIT_CONFIG_COUNT,GIT_CONFIG_KEY_0,GIT_CONFIG_VALUE_0,GIT_CONFIG_KEY_1,GIT_CONFIG_VALUE_1
